# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
env:
  global:
    - CORE_RELEASE=master

matrix:
  include:
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
        - PHPUNIT_TEST=1
    - php: 7.0
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
    - php: 7.1
      env:
        - DB=MYSQL
        - PHPUNIT_TEST=1
    - php: 7.0
      env: DB=PGSQL
        - PHPUNIT_TEST=1
    - php: 7.0
      env:
        - DB=MYSQL
        - BEHAT_TEST=1
  allow_failures:
    # TODO: Migrate tests to behat 3
    - php: 7.0
      env:
        - DB=MYSQL
        - BEHAT_TEST=1

before_script:
  - composer validate
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - if [[ $PHPUNIT_TEST ]]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi
  - if [[ $BEHAT_TEST ]]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension:~2,silverstripe/cms; fi
  - cd ~/builds/ss
  - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
  - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script:
  - if [[ $BEHAT_TEST ]]; then vendor/bin/phpunit siteconfig/tests/php; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @siteconfig; fi
  - if [[ $PHPCS_TEST ]]; then (cd siteconfig && composer run-script lint); fi
